server:
  port: 8761
spring:
  application:
    name: mars-eureka-server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # 使用ip注册
    lease-renewal-interval-in-seconds: 30 # 心跳时间间隔
  client:
    register-with-eureka: false #默认true，单机环境设置为false，表示不向注册中心注册自己
    fetch-registry: false #默认true，单机环境设置为false，表示不需要向注册中心检索自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    eureka-service-url-poll-interval-seconds: 60 # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    registry-fetch-interval-seconds: 5  # 定义从注册中心获取注册服务的信息
  server:
    enable-self-preservation: true # 关闭自我保护模式
    eviction-interval-timer-in-ms: 3000   # 设置清理间隔,单位为毫秒,默认为0
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 6000
